server:
  port: 8080

# 百度翻译
baidu-trans:
  appId: "**************"
  secretKey: "*************"

# 百度语音ASR
baidu-asr:
  appId: "*******"
  apiKey: "******************"
  secretKey: "***********************"
  langEn: 1737
  langJp: 10001

audio:
  captureDeviceName: "Voicemeeter In 1 (VB-Audio Voicemeeter VAIO)"
  sampleRate: 48000
  sampleBit: 16
  channel: 2
